// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovwkkgewbmvsbjsnkiki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92d2trZ2V3Ym12c2Jqc25raWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzU0NTUsImV4cCI6MjA2NzQ1MTQ1NX0.ZwUNE_xW4gz6-EX6WQlDNFYuYyK4tBqm6LJkyBHqXEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});